### ISSUE TITLE
User can log in

### ISSUE THREAD

**Issue by KelsiePorter** [Streamlined-Turing/streamlined_fe#7]
As a user, when I visit the login page, I want to click the login with Google button so that I can login to the application using my google account.

First time users are redirected '/create'
Existing users are redirected to their dashboard

- [ ] Create user table with name, email, and token columns
- [ ] Implement google Omniauth strategy
- [ ] Route for login page is /login
- [ ] User should be redirected to /dashboard after successful login
- [ ] If user is not able to authenticate with google, user should see flash message that reads Oops something went wrong!

![Image](https://user-images.githubusercontent.com/110859604/220507573-822a43e2-b4fd-4ac5-9ccf-b7fb05ca8aa4.jpg)

**Comment by Tscasady** [comment]
This story was subsumed by Landing Page / Oauth issues. Archiving.
